[package]
name = "permuter"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
rand = "0.9.1"
rayon = "1.10.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
# strip = true
debug = true
